#!/bin/bash
USER=manabu.takara@a-lim.co.jp
OWNER=takraalim
REPOSITORY=test
curl \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token ${TOKEN}" \
  "https://api.github.com/repos/${OWNER}/${REPOSITORY}/pulls/4"
