#!/bin/bash
USER=manabu.takara@a-lim.co.jp
OWNER=takraalim
REPOSITORY=test
curl \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token ${TOKEN}" \
  "https://api.github.com/repos/${OWNER}/${REPOSITORY}/pulls" \
  -d '{"head": "a04","base": "main", "title": "レビュー一覧取得"}'
